In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sns
sns.set()

In [2]:
raw_data = pd.read_csv('creditcard.csv')

In [3]:
raw_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [4]:
data = raw_data.copy()

In [5]:
inputs = data.iloc[:,1:-1]
targets = data.iloc[:,-2:]
targets = targets.drop(['Amount'],axis=1)

In [6]:
target_1 = int(np.sum(targets))

In [7]:
target_0_counter = 0
nump_inputs = inputs.to_numpy()
nump_targets = targets.to_numpy()

In [8]:
indices_to_remove = []

In [9]:
for i in range(nump_targets.shape[0]):
    if nump_targets[i] == 0:
        target_0_counter += 1
        if target_0_counter > target_1:
            indices_to_remove.append(i)

In [10]:
inputs_balanced = np.delete(nump_inputs, indices_to_remove, axis=0)   
targets_balanced = np.delete(nump_targets, indices_to_remove, axis=0)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs_balanced, targets_balanced, train_size=0.8 , shuffle=True, random_state=20)

In [12]:
reg = LogisticRegression(max_iter=500)
oned_y_train = np.ravel(y_train)

reg.fit(x_train,oned_y_train)

LogisticRegression(max_iter=500)

In [13]:
reg.score(x_train,oned_y_train)

0.96569250317662

In [14]:
reg.intercept_

array([-2.34129665])

In [15]:
reg.coef_

array([[ 1.02935735e-01, -2.83095264e-01, -8.53969119e-01,
         7.35254080e-01,  1.30992583e-02, -5.15251535e-01,
         2.01661852e-01, -5.52843505e-01, -9.96226548e-02,
        -4.45238955e-01,  9.51559982e-02, -1.14980119e+00,
         5.66574451e-02, -3.24471914e-01, -6.52295490e-01,
         6.65556209e-02,  2.03204280e-01,  5.00822214e-01,
        -1.65266841e-01, -6.75815064e-01, -2.21079592e-01,
         1.16638506e+00,  5.22338085e-01, -7.69711940e-01,
        -8.22372207e-01,  2.71549273e-01, -8.46102392e-01,
         7.03860231e-01,  3.44554274e-04]])

In [16]:
feature_name = inputs.columns
summary_table25 = pd.DataFrame(columns=['Feature Name'],data = feature_name)

In [17]:
summary_table25['Coefficient'] = np.transpose(reg.coef_)

In [18]:
summary_table25.index = summary_table25.index + 1
summary_table25.loc[0] = ['Intercept',reg.intercept_[0]]

In [19]:
summary_table25 = summary_table25.sort_values('Coefficient', ascending=False)
summary_table25.to_excel("summary_table25.xlsx")
summary_table25

   Feature Name  Coefficient
22          V22     1.166385
4            V4     0.735254
28          V28     0.703860
23          V23     0.522338
18          V18     0.500822
26          V26     0.271549
17          V17     0.203204
7            V7     0.201662
1            V1     0.102936
11          V11     0.095156
16          V16     0.066556
13          V13     0.056657
5            V5     0.013099
29       Amount     0.000345
9            V9    -0.099623
19          V19    -0.165267
21          V21    -0.221080
2            V2    -0.283095
14          V14    -0.324472
10          V10    -0.445239
6            V6    -0.515252
8            V8    -0.552844
15          V15    -0.652295
20          V20    -0.675815
24          V24    -0.769712
25          V25    -0.822372
27          V27    -0.846102
3            V3    -0.853969
12          V12    -1.149801
0     Intercept    -2.341297

In [20]:
reg.score(x_test,y_test)

0.9543147208121827